import Nav from "../components/Nav";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
export default function RootLayout({children}: any) {
    return (
        <html lang="en" className="bg-bg-primary">
        <body>
        <div className="max-w-[82%] mx-auto ">
            <Nav/>
            <main>{children}</main>
        </div>
        </body>
        </html>
    )
}
